---- Insert record PRENOTAZIONI

Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (1,3,TO_DATE('2019/08/10 18:02:44', 'yyyy/mm/dd hh24:mi:ss'), 0, 'DURANTE UN BALLO DI GRUPPO ALLA SAGRA DI PAESE, IL PAZIENTE SI E SLOGATO LA CAVIGLIA');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (2,2,TO_DATE('2019/08/10 15:30:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE NECESSITA DI UN MASSAGGIO CON OLIO BOLLENTE');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (3,1,TO_DATE('2019/08/10 14:15:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE HA UN DOLORINO LOMBARE');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (4,1,TO_DATE('2019/08/10 17:14:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE HA MALE ALLA SPALLA, FORSE MORIRA');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (1,2,TO_DATE('2019/08/11 10:12:44', 'yyyy/mm/dd hh24:mi:ss'), 0, 'IL PAZIENTE SI E LANCIATO DALLA FINESTRA CREDENDOSI SPIDERMAN');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (2,3,TO_DATE('2019/08/11 08:02:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE SI E CHIUSO LA MANO DESTRA IN UN CASSETTO ED E DISPERATO');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (3,3,TO_DATE('2019/08/11 12:02:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE SI E ROTTO IL GINOCCHIO FACENDO UNA PIROETTA SU UNA SEDIA ROTANTE');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (4,2,TO_DATE('2019/08/11 13:02:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'STANDO TROPPO TEMPO SEDUTO MALE, IL PAZIENTE HA SVILUPPATO UN FORTE DOLORE ALLA SCHIENA');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (4,1,TO_DATE('2019/08/11 15:30:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'DA UN GRANDE DOLORE DERIVANO GRANDI BESTEMMIE');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (3,3,TO_DATE('2019/08/11 17:02:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'DURANTE UNA GENEROSA MANGIATA, IL PAZIENTE SI E SLOGATO LA MASCELLA');

---- Insert record TERAPIE_AMBULATORI

Insert into TERAPIE_AMBULATORI (ID_TERAPIA, ID_AMBULATORIO) values (1,4);
Insert into TERAPIE_AMBULATORI (ID_TERAPIA, ID_AMBULATORIO) values (2,3);
Insert into TERAPIE_AMBULATORI (ID_TERAPIA, ID_AMBULATORIO) values (3,2);
Insert into TERAPIE_AMBULATORI (ID_TERAPIA, ID_AMBULATORIO) values (4,1);

--- Insert record ANAGRAFICHE

Insert into ANAGRAFICHE (ID, NOME, COGNOME , DATA_NASCITA, CF, N_CELLULARE) values (1,'FRANCESCO','TOTTI',to_date('27-SET-76','DD-MON-RR'),'TTTFNC76P27H501J','3310101010');
Insert into ANAGRAFICHE (ID, NOME, COGNOME , DATA_NASCITA, CF, N_CELLULARE) values (2,'MASSIMO','BOLDI',to_date('23-LUG-45','DD-MON-RR'),'BLDMSM45CIP0LL1N','3336666666');
Insert into ANAGRAFICHE (ID, NOME, COGNOME , DATA_NASCITA, CF, N_CELLULARE) values (3,'MASSIMO','LOPEZ',to_date('11-GEN-52','DD-MON-RR'),'LPZMSM52D0VEST4H','3381234567');
Insert into ANAGRAFICHE (ID, NOME, COGNOME , DATA_NASCITA, CF, N_CELLULARE) values (4,'RAIMONDO','VIANELLO',to_date('7-MAG-22','DD-MON-RR'),'VNLRMN22EM0RT000','3350008000');
Insert into ANAGRAFICHE (ID, NOME, COGNOME , DATA_NASCITA, CF, N_CELLULARE) values (5,'EZIO','GREGGIO',to_date('07-APR-54','DD-MON-RR'),'GRGZIO54LEV3L1NE','3345544554');
Insert into ANAGRAFICHE (ID, NOME, COGNOME , DATA_NASCITA, CF, N_CELLULARE) values (6,'DILETTA','LEOTTA',to_date('16-AGO-91','DD-MON-RR'),'LTTDLT91KEFIKAA4','3334447738');
Insert into ANAGRAFICHE (ID, NOME, COGNOME , DATA_NASCITA, CF, N_CELLULARE) values (7,'ENRICO','MENTANA',to_date('15-GEN-55','DD-MON-RR'),'MNTNRC55M4R4T0NA','3377755577'); 
Insert into ANAGRAFICHE (ID, NOME, COGNOME , DATA_NASCITA, CF, N_CELLULARE) values (8,'VITTORIO','BRUMOTTI',to_date('14-GIU-80','DD-MON-RR'),'BRMVTT80B0MB4ZZA','3339876543'); 
Insert into ANAGRAFICHE (ID, NOME, COGNOME , DATA_NASCITA, CF, N_CELLULARE) values (9,'CRISTINA','CHIABOTTO',to_date('15-SET-86','DD-MON-RR'),'CHBCRS86M155IT4L','3479182735'); 

--- Insert record MEDICI_TERAPIE

Insert into MEDICI_TERAPIE (ID_MEDICO, ID_TERAPIA) values (1, 2); 
Insert into MEDICI_TERAPIE (ID_MEDICO, ID_TERAPIA) values (1, 3);
Insert into MEDICI_TERAPIE (ID_MEDICO, ID_TERAPIA) values (2, 1);
Insert into MEDICI_TERAPIE (ID_MEDICO, ID_TERAPIA) values (3, 3);
Insert into MEDICI_TERAPIE (ID_MEDICO, ID_TERAPIA) values (3, 4); 

---Insert record AMBULATORI
INSERT INTO AMBULATORI (ID, NOME) VALUES (2, 'GIALLO');
INSERT INTO AMBULATORI (ID, NOME) VALUES (1, 'ROSSO');
INSERT INTO AMBULATORI (ID, NOME) VALUES (4, 'VERDE');
INSERT INTO AMBULATORI (ID, NOME) VALUES (3, 'BLU');

--- Insert record TERAPIE
INSERT INTO TERAPIE (ID, NOME) VALUES (4, 'GINNASTICA POSTURALE');
INSERT INTO TERAPIE (ID, NOME) VALUES (3, 'MASSOTERAPIA');
INSERT INTO TERAPIE (ID, NOME) VALUES (1, 'LASERTERAPIA');
INSERT INTO TERAPIE (ID, NOME) VALUES (2, 'ELETTROSTIMOLAZIONI');

--- Insert record STAFF
INSERT INTO STAFF (ID, ID_ANAG, LIVELLO) VALUES (1, 4, 0);
INSERT INTO STAFF (ID, ID_ANAG, LIVELLO) VALUES (2, 5, 1);
INSERT INTO STAFF (ID, ID_ANAG, LIVELLO) VALUES (3, 6, 1);


--- Insert record MEDICI
INSERT INTO MEDICI (ID,ID_ANAG,ISMEDICO) VALUES (1,1,1);
INSERT INTO MEDICI (ID,ID_ANAG,ISMEDICO) VALUES (2,2,0);
INSERT INTO MEDICI (ID,ID_ANAG,ISMEDICO) VALUES (3,3,1);
