---- Insert record PRENOTAZIONI

Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (1,3,TO_DATE('2019/08/10 18:02:44', 'yyyy/mm/dd hh24:mi:ss'), O, 'DURANTE UN BALLO DI GRUPPO ALLA SAGRA DI PAESE, IL PAZIENTE SI E SLOGATO LA CAVIGLIA');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (2,2,TO_DATE('2019/08/10 15:30:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE NECESSITA DI UN MASSAGGIO CON OLIO BOLLENTE');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (3,1,TO_DATE('2019/08/10 14:15:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE HA UN DOLORINO LOMBARE');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (4,1,TO_DATE('2019/08/10 17:14:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE HA MALE ALLA SPALLA, FORSE MORIRA');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (1,2,TO_DATE('2019/08/11 10:12:44', 'yyyy/mm/dd hh24:mi:ss'), 0, 'IL PAZIENTE SI E LANCIATO DALLA FINESTRA CREDENDOSI SPIDERMAN');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (2,3,TO_DATE('2019/08/11 08:02:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE SI E CHIUSO LA MANO DESTRA IN UN CASSETTO ED E DISPERATO');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (3,3,TO_DATE('2019/08/11 12:02:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'IL PAZIENTE SI E ROTTO IL GINOCCHIO FACENDO UNA PIROETTA SU UNA SEDIA ROTANTE');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (4,2,TO_DATE('2019/08/11 13:02:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'STANDO TROPPO TEMPO SEDUTO MALE, IL PAZIENTE HA SVILUPPATO UN FORTE DOLORE ALLA SCHIENA');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (4,1,TO_DATE('2019/08/11 15:30:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'DA UN GRANDE DOLORE DERIVANO GRANDI BESTEMMIE');
Insert into PRENOTAZIONI (ID_AMBULATORIO, ID_CLIENTE, DATA_ORA, ATTIVO, PATOLOGIA) values (3,3,TO_DATE('2019/08/11 17:02:44', 'yyyy/mm/dd hh24:mi:ss'), 1, 'DURANTE UNA GENEROSA MANGIATA, IL PAZIENTE SI E SLOGATO LA MASCELLA');

---- Insert record TERAPIE_AMBULATORI

Insert into TERAPIE_AMBULATORI (ID_TERAPIA, ID_AMBULATORIO) values (1,4);
Insert into TERAPIE_AMBULATORI (ID_TERAPIA, ID_AMBULATORIO) values (2,3);
Insert into TERAPIE_AMBULATORI (ID_TERAPIA, ID_AMBULATORIO) values (3,2);
Insert into TERAPIE_AMBULATORI (ID_TERAPIA, ID_AMBULATORIO) values (4,1);

--- Insert record 
