--------------------------------------------------------
--  File creato - martedì-agosto-06-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_AMBULATORI
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_AMBULATORI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ANAGRAFICHE
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ANAGRAFICHE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTI
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_CLIENTI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEDICI
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MEDICI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STAFF
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_STAFF"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TERAPIE
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_TERAPIE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AMBULATORI
--------------------------------------------------------

  CREATE TABLE "AMBULATORI" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANAGRAFICHE
--------------------------------------------------------

  CREATE TABLE "ANAGRAFICHE" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(30 BYTE), 
	"COGNOME" VARCHAR2(30 BYTE), 
	"DATA_NASCITA" DATE, 
	"CF" VARCHAR2(16 BYTE), 
	"N_CELLULARE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTI
--------------------------------------------------------

  CREATE TABLE "CLIENTI" 
   (	"ID" NUMBER, 
	"ID_ANAG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICI
--------------------------------------------------------

  CREATE TABLE "MEDICI" 
   (	"ID" NUMBER, 
	"ID_ANAG" NUMBER, 
	"ISMEDICO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICI_TERAPIE
--------------------------------------------------------

  CREATE TABLE "MEDICI_TERAPIE" 
   (	"ID_MEDICO" NUMBER, 
	"ID_TERAPIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRENOTAZIONI
--------------------------------------------------------

  CREATE TABLE "PRENOTAZIONI" 
   (	"ID_AMBULATORI" NUMBER, 
	"ID_CLIENTI" NUMBER, 
	"DATA_ORA" DATE, 
	"ATTIVO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "STAFF" 
   (	"ID" NUMBER, 
	"ID_ANAG" NUMBER, 
	"LIVELLO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TERAPIE
--------------------------------------------------------

  CREATE TABLE "TERAPIE" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TERAPIE_AMBULATORI
--------------------------------------------------------

  CREATE TABLE "TERAPIE_AMBULATORI" 
   (	"ID_TERAPIA" NUMBER, 
	"ID_AMBULATORIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AMBULATORI
SET DEFINE OFF;
Insert into AMBULATORI (ID,NOME) values ('1','Policlinico Gemelli');
REM INSERTING into ANAGRAFICHE
SET DEFINE OFF;
Insert into ANAGRAFICHE (ID,NOME,COGNOME,DATA_NASCITA,CF,N_CELLULARE) values ('1','Francesco','Truono',to_date('09-GIU-97','DD-MON-RR'),'TRNSGGDJ',null);
Insert into ANAGRAFICHE (ID,NOME,COGNOME,DATA_NASCITA,CF,N_CELLULARE) values ('2','Bovino','Romino',to_date('06-AGO-19','DD-MON-RR'),'HGDGHGS',null);
Insert into ANAGRAFICHE (ID,NOME,COGNOME,DATA_NASCITA,CF,N_CELLULARE) values ('3','Ilberto','Medico',to_date('01-AGO-19','DD-MON-RR'),'GJHDBHW','33387098');
REM INSERTING into CLIENTI
SET DEFINE OFF;
Insert into CLIENTI (ID,ID_ANAG) values ('1','1');
Insert into CLIENTI (ID,ID_ANAG) values ('2','2');
REM INSERTING into MEDICI
SET DEFINE OFF;
Insert into MEDICI (ID,ID_ANAG,ISMEDICO) values ('1','3','1');
REM INSERTING into MEDICI_TERAPIE
SET DEFINE OFF;
Insert into MEDICI_TERAPIE (ID_MEDICO,ID_TERAPIA) values ('1','1');
REM INSERTING into PRENOTAZIONI
SET DEFINE OFF;
Insert into PRENOTAZIONI (ID_AMBULATORI,ID_CLIENTI,DATA_ORA,ATTIVO) values ('1','1',to_date('23-AGO-19','DD-MON-RR'),'1');
REM INSERTING into STAFF
SET DEFINE OFF;
Insert into STAFF (ID,ID_ANAG,LIVELLO) values ('1','3','1');
REM INSERTING into TERAPIE
SET DEFINE OFF;
Insert into TERAPIE (ID,NOME) values ('1','Spezza Gambe');
Insert into TERAPIE (ID,NOME) values ('2','Aggiusta mani');
Insert into TERAPIE (ID,NOME) values ('3','Massaggio Bello');
REM INSERTING into TERAPIE_AMBULATORI
SET DEFINE OFF;
Insert into TERAPIE_AMBULATORI (ID_TERAPIA,ID_AMBULATORIO) values ('2','1');
--------------------------------------------------------
--  DDL for Index PK_ID_AMBULATORI
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID_AMBULATORI" ON "AMBULATORI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_ANAG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID_ANAG" ON "ANAGRAFICHE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID_CLIENT" ON "CLIENTI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_MEDIC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID_MEDIC" ON "MEDICI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_MT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID_MT" ON "MEDICI_TERAPIE" ("ID_MEDICO", "ID_TERAPIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_PRENOTAZIONI
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID_PRENOTAZIONI" ON "PRENOTAZIONI" ("ID_AMBULATORI", "ID_CLIENTI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_STAFF
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID_STAFF" ON "STAFF" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID_TA" ON "TERAPIE_AMBULATORI" ("ID_TERAPIA", "ID_AMBULATORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TERAPIE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID_TERAPIE" ON "TERAPIE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger AMBULATORI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AMBULATORI_TRG" 
	BEFORE INSERT ON AMBULATORI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_AMBULATORI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "AMBULATORI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ANAGRAFICHE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ANAGRAFICHE_TRG" 
	BEFORE INSERT ON ANAGRAFICHE
	FOR EACH ROW
BEGIN
  SELECT "SEQ_ANAGRAFICHE".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "ANAGRAFICHE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CLIENTI_TRG" 
	BEFORE INSERT ON CLIENTI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_CLIENTI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "CLIENTI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEDICI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICI_TRG" 
	BEFORE INSERT ON MEDICI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_MEDICI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "MEDICI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STAFF_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "STAFF_TRG" 
	BEFORE INSERT ON STAFF
	FOR EACH ROW
BEGIN
  SELECT "SEQ_STAFF".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "STAFF_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TERAPIE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TERAPIE_TRG" 
	BEFORE INSERT ON TERAPIE
	FOR EACH ROW
BEGIN
  SELECT "SEQ_TERAPIE".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "TERAPIE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table AMBULATORI
--------------------------------------------------------

  ALTER TABLE "AMBULATORI" ADD CONSTRAINT "PK_ID_AMBULATORI" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AMBULATORI" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANAGRAFICHE
--------------------------------------------------------

  ALTER TABLE "ANAGRAFICHE" ADD CONSTRAINT "PK_ID_ANAG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANAGRAFICHE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTI
--------------------------------------------------------

  ALTER TABLE "CLIENTI" ADD CONSTRAINT "PK_ID_CLIENT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLIENTI" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICI
--------------------------------------------------------

  ALTER TABLE "MEDICI" ADD CONSTRAINT "PK_ID_MEDIC" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEDICI" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICI_TERAPIE
--------------------------------------------------------

  ALTER TABLE "MEDICI_TERAPIE" ADD CONSTRAINT "PK_ID_MT" PRIMARY KEY ("ID_MEDICO", "ID_TERAPIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEDICI_TERAPIE" MODIFY ("ID_TERAPIA" NOT NULL ENABLE);
  ALTER TABLE "MEDICI_TERAPIE" MODIFY ("ID_MEDICO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRENOTAZIONI
--------------------------------------------------------

  ALTER TABLE "PRENOTAZIONI" ADD CONSTRAINT "PK_ID_PRENOTAZIONI" PRIMARY KEY ("ID_AMBULATORI", "ID_CLIENTI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PRENOTAZIONI" MODIFY ("ID_AMBULATORI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "STAFF" ADD CONSTRAINT "PK_ID_STAFF" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "STAFF" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TERAPIE
--------------------------------------------------------

  ALTER TABLE "TERAPIE" ADD CONSTRAINT "PK_ID_TERAPIE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TERAPIE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TERAPIE_AMBULATORI
--------------------------------------------------------

  ALTER TABLE "TERAPIE_AMBULATORI" ADD CONSTRAINT "PK_ID_TA" PRIMARY KEY ("ID_TERAPIA", "ID_AMBULATORIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TERAPIE_AMBULATORI" MODIFY ("ID_AMBULATORIO" NOT NULL ENABLE);
  ALTER TABLE "TERAPIE_AMBULATORI" MODIFY ("ID_TERAPIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENTI
--------------------------------------------------------

  ALTER TABLE "CLIENTI" ADD CONSTRAINT "FK_ANAG" FOREIGN KEY ("ID_ANAG")
	  REFERENCES "ANAGRAFICHE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICI
--------------------------------------------------------

  ALTER TABLE "MEDICI" ADD CONSTRAINT "FK_ANAG_M" FOREIGN KEY ("ID_ANAG")
	  REFERENCES "ANAGRAFICHE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICI_TERAPIE
--------------------------------------------------------

  ALTER TABLE "MEDICI_TERAPIE" ADD CONSTRAINT "FK_MED_ME" FOREIGN KEY ("ID_MEDICO")
	  REFERENCES "MEDICI" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MEDICI_TERAPIE" ADD CONSTRAINT "FK_TER_ME" FOREIGN KEY ("ID_TERAPIA")
	  REFERENCES "TERAPIE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRENOTAZIONI
--------------------------------------------------------

  ALTER TABLE "PRENOTAZIONI" ADD CONSTRAINT "FK_AMB_P" FOREIGN KEY ("ID_AMBULATORI")
	  REFERENCES "AMBULATORI" ("ID") ENABLE;
  ALTER TABLE "PRENOTAZIONI" ADD CONSTRAINT "FK_CLIENT_P" FOREIGN KEY ("ID_CLIENTI")
	  REFERENCES "CLIENTI" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "STAFF" ADD CONSTRAINT "FK_ANAG_S" FOREIGN KEY ("ID_ANAG")
	  REFERENCES "ANAGRAFICHE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TERAPIE_AMBULATORI
--------------------------------------------------------

  ALTER TABLE "TERAPIE_AMBULATORI" ADD CONSTRAINT "FK_AMB_TA" FOREIGN KEY ("ID_AMBULATORIO")
	  REFERENCES "AMBULATORI" ("ID") ENABLE;
  ALTER TABLE "TERAPIE_AMBULATORI" ADD CONSTRAINT "FK_TER_TA" FOREIGN KEY ("ID_TERAPIA")
	  REFERENCES "TERAPIE" ("ID") ENABLE;
