CREATE TABLE "ANAGRAFICHE" (
"ID"  NUMBER NOT NULL,
"NOME"  VARCHAR2(30 BYTE),
"COGNOME"  VARCHAR2(30 BYTE),
"DATA_NASCITA"  DATE,
"CF" VARCHAR2(16 BYTE),
"N_CELLULARE" VARCHAR2 (15),
CONSTRAINT PK_ID_ANAG PRIMARY KEY (ID)
);

CREATE TABLE "CLIENTI" (
"ID"  NUMBER NOT NULL,
"ID_ANAG"  NUMBER,
CONSTRAINT PK_ID_CLIENT PRIMARY KEY (ID),
CONSTRAINT FK_ANAG
    FOREIGN KEY (ID_ANAG)
    REFERENCES ANAGRAFICHE(ID)
);

CREATE TABLE "AMBULATORI" (
"ID"  NUMBER NOT NULL,
"NOME" VARCHAR2(30 BYTE),
"DATA_ORA" DATE,
"ATTIVO" NUMBER,
CONSTRAINT PK_ID_AMBULATORI PRIMARY KEY (ID)
);

CREATE TABLE "STAFF" (
"ID"  NUMBER NOT NULL,
"ID_ANAG" NUMBER,
"LIVELLO" NUMBER,
CONSTRAINT FK_ANAG_S
    FOREIGN KEY (ID_ANAG)
    REFERENCES ANAGRAFICHE(ID),
CONSTRAINT PK_ID_STAFF PRIMARY KEY (ID)
);

CREATE TABLE "TERAPIE" (
"ID"  NUMBER NOT NULL,
"NOME" VARCHAR2(30 BYTE),
CONSTRAINT PK_ID_TERAPIE PRIMARY KEY (ID)
);

CREATE TABLE "PRENOTAZIONI" (
"ID_AMBULATORI"  NUMBER NOT NULL,
"ID_CLIENTI" NUMBER NOT NULL,
"DATA_ORA" DATE,
"ATTIVO" NUMBER,
CONSTRAINT FK_AMB_P
    FOREIGN KEY (ID_AMBULATORI)
    REFERENCES AMBULATORI(ID),
CONSTRAINT FK_CLIENT_P
    FOREIGN KEY (ID_CLIENTI)
    REFERENCES CLIENTI(ID),
CONSTRAINT PK_ID_PRENOTAZIONI PRIMARY KEY (ID_AMBULATORI,ID_CLIENTI)
);

CREATE TABLE "MEDICI" (
"ID"  NUMBER NOT NULL,
"ID_ANAG" NUMBER,
"ISMEDICO" NUMBER,
CONSTRAINT PK_ID_MEDIC PRIMARY KEY (ID),
CONSTRAINT FK_ANAG_M
    FOREIGN KEY (ID_ANAG)
    REFERENCES ANAGRAFICHE(ID)
);

CREATE TABLE "MEDICI_TERAPIE" (
"ID_MEDICO"  NUMBER NOT NULL,
"ID_TERAPIA" NUMBER NOT NULL,
CONSTRAINT FK_MED_ME
    FOREIGN KEY (ID_MEDICO)
    REFERENCES MEDICI(ID),
CONSTRAINT FK_TER_ME
    FOREIGN KEY (ID_TERAPIA)
    REFERENCES TERAPIE(ID),
CONSTRAINT PK_ID_MT PRIMARY KEY (ID_MEDICO,ID_TERAPIA)
);

CREATE TABLE "TERAPIE_AMBULATORI" (
"ID_TERAPIA" NUMBER NOT NULL,
"ID_AMBULATORIO"  NUMBER NOT NULL,
CONSTRAINT FK_AMB_TA
    FOREIGN KEY (ID_AMBULATORIO)
    REFERENCES AMBULATORI(ID),
CONSTRAINT FK_TER_TA
    FOREIGN KEY (ID_TERAPIA)
    REFERENCES TERAPIE(ID),
CONSTRAINT PK_ID_TA PRIMARY KEY (ID_TERAPIA,ID_AMBULATORIO)
);