-------------------------------
	--	DB Settings
-------------------------------

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;  
CREATE USER FIST IDENTIFIED BY ORACLE;
GRANT CONNECT TO FIST;
GRANT RESOURCE,DBA TO FIST;

-------------------------------
	--	ANAGRAFICHE
-------------------------------

CREATE TABLE "ANAGRAFICHE" (
"ID"  NUMBER NOT NULL,
"NOME"  VARCHAR2(30 BYTE),
"COGNOME"  VARCHAR2(30 BYTE),
"DATA_NASCITA"  DATE,
"CF" VARCHAR2(16 BYTE),
"N_CELLULARE" VARCHAR2 (15),
CONSTRAINT PK_ID_ANAG PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX "ANAGRAFICHE_PK" ON "ANAGRAFICHE" ("ID");
--ALTER TABLE "AUTISTI" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "ANAGRAFICHE" ADD CONSTRAINT "ANAGRAFICHE_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_ANAGRAFICHE" START WITH 1;

CREATE OR REPLACE TRIGGER "ANAGRAFICHE_TRG" 
	BEFORE INSERT ON ANAGRAFICHE
	FOR EACH ROW
BEGIN
  SELECT "SEQ_ANAGRAFICHE".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "ANAGRAFICHE_TRG" ENABLE;

-------------------------------
	--	CLIENTI
-------------------------------

CREATE TABLE "CLIENTI" (
"ID"  NUMBER NOT NULL,
"ID_ANAG"  NUMBER,
CONSTRAINT PK_ID_CLIENT PRIMARY KEY (ID),
CONSTRAINT FK_ANAG
    FOREIGN KEY (ID_ANAG)
    REFERENCES ANAGRAFICHE(ID)
);

CREATE UNIQUE INDEX "CLIENTI_PK" ON "CLIENTI" ("ID");
ALTER TABLE "CLIENTI" ADD CONSTRAINT "CLIENTI_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_CLIENTI" START WITH 1;

CREATE OR REPLACE TRIGGER "CLIENTI_TRG" 
	BEFORE INSERT ON CLIENTI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_CLIENTI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "CLIENTI_TRG" ENABLE;

-------------------------------
	--	AMBULATORI
-------------------------------

CREATE TABLE "AMBULATORI" (
"ID"  NUMBER NOT NULL,
"NOME" VARCHAR2(30 BYTE),
"DATA_ORA" DATE,
"ATTIVO" NUMBER,
CONSTRAINT PK_ID_AMBULATORI PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX "AMBULATORI_PK" ON "AMBULATORI" ("ID");
ALTER TABLE "AMBULATORI" ADD CONSTRAINT "AMBULATORI_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_AMBULATORI" START WITH 1;

CREATE OR REPLACE TRIGGER "AMBULATORI_TRG" 
	BEFORE INSERT ON AMBULATORI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_AMBULATORI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "AMBULATORI_TRG" ENABLE;

-------------------------------
	--	STAFF
-------------------------------

CREATE TABLE "STAFF" (
"ID"  NUMBER NOT NULL,
"ID_ANAG" NUMBER,
"LIVELLO" NUMBER,
CONSTRAINT FK_ANAG_S
    FOREIGN KEY (ID_ANAG)
    REFERENCES ANAGRAFICHE(ID),
CONSTRAINT PK_ID_STAFF PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX "STAFF_PK" ON "STAFF" ("ID");
ALTER TABLE "STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_STAFF" START WITH 1;

CREATE OR REPLACE TRIGGER "STAFF_TRG" 
	BEFORE INSERT ON STAFF
	FOR EACH ROW
BEGIN
  SELECT "SEQ_STAFF".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "STAFF_TRG" ENABLE;

-------------------------------
	--	TERAPIE
-------------------------------

CREATE TABLE "TERAPIE" (
"ID"  NUMBER NOT NULL,
"NOME" VARCHAR2(30 BYTE),
CONSTRAINT PK_ID_TERAPIE PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX "TERAPIE_PK" ON "TERAPIE" ("ID");
ALTER TABLE "TERAPIE" ADD CONSTRAINT "TERAPIE_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_TERAPIE" START WITH 1;

CREATE OR REPLACE TRIGGER "TERAPIE_TRG" 
	BEFORE INSERT ON TERAPIE
	FOR EACH ROW
BEGIN
  SELECT "SEQ_TERAPIE".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "TERAPIE_TRG" ENABLE;

-------------------------------
	--	PRENOTAZIONI
-------------------------------

CREATE TABLE "PRENOTAZIONI" (
"ID_AMBULATORI"  NUMBER NOT NULL,
"ID_CLIENTI" NUMBER NOT NULL,
"DATA_ORA" DATE,
"ATTIVO" NUMBER,
CONSTRAINT FK_AMB_P
    FOREIGN KEY (ID_AMBULATORI)
    REFERENCES AMBULATORI(ID),
CONSTRAINT FK_CLIENT_P
    FOREIGN KEY (ID_CLIENTI)
    REFERENCES CLIENTI(ID),
CONSTRAINT PK_ID_PRENOTAZIONI PRIMARY KEY (ID_AMBULATORI,ID_CLIENTI)
);

-------------------------------
	--	MEDICO(ID(PK), ID_ANAG(FK), ISMEDICO)
-------------------------------

CREATE TABLE "MEDICI" (
"ID"  NUMBER NOT NULL,
"ID_ANAG" NUMBER,
"ISMEDICO" NUMBER,
CONSTRAINT PK_ID_MEDIC PRIMARY KEY (ID),
CONSTRAINT FK_ANAG_M
    FOREIGN KEY (ID_ANAG)
    REFERENCES ANAGRAFICHE(ID)
);

CREATE UNIQUE INDEX "MEDICI_PK" ON "MEDICI" ("ID");
ALTER TABLE "MEDICI" ADD CONSTRAINT "MEDICI_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_MEDICI" START WITH 1;

CREATE OR REPLACE TRIGGER "MEDICI_TRG" 
	BEFORE INSERT ON MEDICI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_MEDICI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "MEDICI_TRG" ENABLE;

-------------------------------
	--	MEDICO_TERAPIA
-------------------------------

CREATE TABLE "MEDICI_TERAPIE" (
"ID_MEDICO"  NUMBER NOT NULL,
"ID_TERAPIA" NUMBER NOT NULL,
CONSTRAINT FK_MED_ME
    FOREIGN KEY (ID_MEDICO)
    REFERENCES MEDICI(ID),
CONSTRAINT FK_TER_ME
    FOREIGN KEY (ID_TERAPIA)
    REFERENCES TERAPIE(ID),
CONSTRAINT PK_ID_MT PRIMARY KEY (ID_MEDICO,ID_TERAPIA)
);

-------------------------------
	--	TERAPIE_AMBULATORI
-------------------------------

CREATE TABLE "TERAPIE_AMBULATORI" (
"ID_TERAPIA" NUMBER NOT NULL,
"ID_AMBULATORIO"  NUMBER NOT NULL,
CONSTRAINT FK_AMB_TA
    FOREIGN KEY (ID_AMBULATORIO)
    REFERENCES AMBULATORI(ID),
CONSTRAINT FK_TER_TA
    FOREIGN KEY (ID_TERAPIA)
    REFERENCES TERAPIE(ID),
CONSTRAINT PK_ID_TA PRIMARY KEY (ID_TERAPIA,ID_AMBULATORIO)
);