-------------------------------
	--	ANAGRAFICHE
-------------------------------

CREATE UNIQUE INDEX "ANAGRAFICHE_PK" ON "ANAGRAFICHE" ("ID");
--ALTER TABLE "AUTISTI" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "ANAGRAFICHE" ADD CONSTRAINT "ANAGRAFICHE_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_ANAGRAFICHE" START WITH 1;

CREATE OR REPLACE TRIGGER "ANAGRAFICHE_TRG" 
	BEFORE INSERT ON ANAGRAFICHE
	FOR EACH ROW
BEGIN
  SELECT "SEQ_ANAGRAFICHE".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "ANAGRAFICHE_TRG" ENABLE;

-------------------------------
	--	CLIENTI
-------------------------------

CREATE UNIQUE INDEX "CLIENTI_PK" ON "CLIENTI" ("ID");
ALTER TABLE "CLIENTI" ADD CONSTRAINT "CLIENTI_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_CLIENTI" START WITH 1;

CREATE OR REPLACE TRIGGER "CLIENTI_TRG" 
	BEFORE INSERT ON CLIENTI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_CLIENTI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "CLIENTI_TRG" ENABLE;

-------------------------------
	--	AMBULATORI
-------------------------------

CREATE UNIQUE INDEX "AMBULATORI_PK" ON "AMBULATORI" ("ID");
ALTER TABLE "AMBULATORI" ADD CONSTRAINT "AMBULATORI_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_AMBULATORI" START WITH 1;

CREATE OR REPLACE TRIGGER "AMBULATORI_TRG" 
	BEFORE INSERT ON AMBULATORI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_AMBULATORI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "AMBULATORI_TRG" ENABLE;

-------------------------------
	--	MEDICI
-------------------------------

CREATE UNIQUE INDEX "MEDICI_PK" ON "MEDICI" ("ID");
ALTER TABLE "MEDICI" ADD CONSTRAINT "MEDICI_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_MEDICI" START WITH 1;

CREATE OR REPLACE TRIGGER "MEDICI_TRG" 
	BEFORE INSERT ON MEDICI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_MEDICI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "MEDICI_TRG" ENABLE;

-------------------------------
	--	TERAPIE
-------------------------------

CREATE UNIQUE INDEX "TERAPIE_PK" ON "TERAPIE" ("ID");
ALTER TABLE "TERAPIE" ADD CONSTRAINT "TERAPIE_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_TERAPIE" START WITH 1;

CREATE OR REPLACE TRIGGER "TERAPIE_TRG" 
	BEFORE INSERT ON TERAPIE
	FOR EACH ROW
BEGIN
  SELECT "SEQ_TERAPIE".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "TERAPIE_TRG" ENABLE;

-------------------------------
	--	STAFF
-------------------------------

CREATE UNIQUE INDEX "STAFF_PK" ON "STAFF" ("ID");
ALTER TABLE "STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("ID");

CREATE  SEQUENCE "SEQ_STAFF" START WITH 1;

CREATE OR REPLACE TRIGGER "STAFF_TRG" 
	BEFORE INSERT ON STAFF
	FOR EACH ROW
BEGIN
  SELECT "SEQ_STAFF".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "STAFF_TRG" ENABLE;