-------------------------------
	--	ANAGRAFICHE
-------------------------------

CREATE  SEQUENCE "SEQ_ANAGRAFICHE" START WITH 1;

CREATE OR REPLACE TRIGGER "ANAGRAFICHE_TRG" 
	BEFORE INSERT ON ANAGRAFICHE
	FOR EACH ROW
BEGIN
  SELECT "SEQ_ANAGRAFICHE".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "ANAGRAFICHE_TRG" ENABLE;

-------------------------------
	--	CLIENTI
-------------------------------

CREATE  SEQUENCE "SEQ_CLIENTI" START WITH 1;

CREATE OR REPLACE TRIGGER "CLIENTI_TRG" 
	BEFORE INSERT ON CLIENTI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_CLIENTI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "CLIENTI_TRG" ENABLE;

-------------------------------
	--	AMBULATORI
-------------------------------

CREATE  SEQUENCE "SEQ_AMBULATORI" START WITH 1;

CREATE OR REPLACE TRIGGER "AMBULATORI_TRG" 
	BEFORE INSERT ON AMBULATORI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_AMBULATORI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "AMBULATORI_TRG" ENABLE;

-------------------------------
	--	MEDICI
-------------------------------

CREATE  SEQUENCE "SEQ_MEDICI" START WITH 1;

CREATE OR REPLACE TRIGGER "MEDICI_TRG" 
	BEFORE INSERT ON MEDICI
	FOR EACH ROW
BEGIN
  SELECT "SEQ_MEDICI".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "MEDICI_TRG" ENABLE;

-------------------------------
	--	TERAPIE
-------------------------------

CREATE  SEQUENCE "SEQ_TERAPIE" START WITH 1;

CREATE OR REPLACE TRIGGER "TERAPIE_TRG" 
	BEFORE INSERT ON TERAPIE
	FOR EACH ROW
BEGIN
  SELECT "SEQ_TERAPIE".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "TERAPIE_TRG" ENABLE;

-------------------------------
	--	STAFF
-------------------------------

CREATE  SEQUENCE "SEQ_STAFF" START WITH 1;

CREATE OR REPLACE TRIGGER "STAFF_TRG" 
	BEFORE INSERT ON STAFF
	FOR EACH ROW
BEGIN
  SELECT "SEQ_STAFF".NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/
ALTER TRIGGER "STAFF_TRG" ENABLE;